# flask-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
       
      containers:
      - name: flask
        image: 164340264957.dkr.ecr.us-east-1.amazonaws.com/finalproject:latest
        ports:
          - containerPort: 81
        env:
          - name: DBHOST
            value: "mysql"
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBUSER
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBPWD
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DATABASE
          - name: DBPORT
            value: "3306"
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: S3_BUCKET
          - name: S3_FILE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: S3_FILE
          - name: MY_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MY_NAME
        volumeMounts:
          - name: aws-creds
            mountPath: /root/.aws/credentials
            subPath: credentials
            readOnly: true
      volumes:
        - name: aws-creds
          secret:
            secretName: aws-creds
            items:
              - key: credentials
                path: credentials
