apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-read-create
  namespace: final
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "watch"]
