apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-clo835
  namespace: final
subjects:
  - kind: ServiceAccount
    name: clo835
    namespace: final
roleRef:
  kind: Role
  name: ns-read-create
  apiGroup: rbac.authorization.k8s.io
