apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: final
type: Opaque
data:
  DBHOST: bG9jYWxob3N0           # echo -n "localhost" | base64
  DBUSER: cm9vdA==               # echo -n "root" | base64
  DBPWD: cGFzc3dvcmQ=            # echo -n "password" | base64
  DATABASE: ZW1wbG95ZWVz         # echo -n "employees" | base64
  DBPORT: MzMwNg==               # echo -n "3306" | base64
